---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - smartcontract.smartcontract.com
  resources:
  - smartcontracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smartcontract.smartcontract.com
  resources:
  - smartcontracts/finalizers
  verbs:
  - update
- apiGroups:
  - smartcontract.smartcontract.com
  resources:
  - smartcontracts/status
  verbs:
  - get
  - patch
  - update
