# permissions for end users to edit smartcontracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: smartcontract-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: smartcontract-editor-role
rules:
- apiGroups:
  - smartcontract.smartcontract.com
  resources:
  - smartcontracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smartcontract.smartcontract.com
  resources:
  - smartcontracts/status
  verbs:
  - get
